"""init schema

Revision ID: 745814f1830c
Revises: 
Create Date: 2025-12-21 18:21:18.325256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '745814f1830c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_preferred_language'), 'user', ['preferred_language'], unique=False)
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_index(op.f('ix_word_language'), 'word', ['language'], unique=False)
    op.create_index(op.f('ix_word_word_text'), 'word', ['word_text'], unique=False)
    op.create_table('reviewlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewlog_next_review_at'), 'reviewlog', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_reviewlog_user_id'), 'reviewlog', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviewlog_word_id'), 'reviewlog', ['word_id'], unique=False)
    op.create_table('story',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_index(op.f('ix_story_language'), 'story', ['language'], unique=False)
    op.create_index(op.f('ix_story_user_id'), 'story', ['user_id'], unique=False)
    op.create_table('storyword',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.story_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('story_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyword')
    op.drop_index(op.f('ix_story_user_id'), table_name='story')
    op.drop_index(op.f('ix_story_language'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_reviewlog_word_id'), table_name='reviewlog')
    op.drop_index(op.f('ix_reviewlog_user_id'), table_name='reviewlog')
    op.drop_index(op.f('ix_reviewlog_next_review_at'), table_name='reviewlog')
    op.drop_table('reviewlog')
    op.drop_index(op.f('ix_word_word_text'), table_name='word')
    op.drop_index(op.f('ix_word_language'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_user_preferred_language'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
